# Autogenerated wrapper script for GAP_pkg_nq_jll for aarch64-linux-musl
export nq

using GMP_jll
JLLWrappers.@generate_wrapper_header("GAP_pkg_nq")
JLLWrappers.@declare_executable_product(nq)
function __init__()
    JLLWrappers.@generate_init_header(GMP_jll)
    JLLWrappers.@init_executable_product(
        nq,
        "bin/nq",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
